name: Setup Android NDK
- steps:
  - uses: actions/checkout@v3
  - uses: nttld/setup-ndk@v1
    with:
      ndk-version: r26d
  - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
