# name: Setup Android NDK modified(export NDK_HOME)
- runs-on: ubuntu-latest
   #steps:
    - uses: actions/checkout@v4
    - uses: HoshinoSuzumi/setup-ndk@v1.5.4
    - with:
    - ndk-version: r29d
    - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
